Update amdgpu firmwares to the latest
FreeBSDDesktop/kms-firmware pull request #16
Opened 2021-02-12 19:55 UTC by juikim

Note the next two commits were support for RDNA2 (Sienna Cichlid) and Cezanne APU (Green Sardine):

https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=54c797a694d3830ef93f349ec25e1d96d4b88102
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=f7915a0c29fee27a310cebd7155b9e3a6eb71a1d

Since we don't support either of them yet, these two commits were intentionally left out.

2021-02-14 09:10 UTC, evadot commented
LGTM

2021-02-14 10:31 UTC, zeising requested changes
Small nit, see inline below.
Also, any chance you can squash the two commits hooking up the new firmware into one commit?

2021-02-15 17:17 UTC, juikim commented on amdgpukmsfw/Makefile
> +	navi14_mec_wks							\
I just sorted it with `LANG=C`.  In fact, it was the only file in wrong order.

2021-02-15 18:24 UTC, juikim commented on amdgpukmsfw/Makefile
> +	navi14_mec_wks							\
> Also, any chance you can squash the two commits hooking up the new firmware into one commit?

Done.

2021-02-16 07:21 UTC, zeising requested changes
History still looks quite strange, it is now 6 commits (one is a merge commit) with three commits related to hooking up the new firmware.

2021-02-16 07:21 UTC, zeising commented on amdgpukmsfw/Makefile
> +	navi14_mec_wks							\
Can you please adjust this so that firmware that goes for the same card is in the same place in the makefile.

2021-02-16 07:35 UTC, zeising commented on amdgpukmsfw/Makefile
> +	navi14_mec_wks							\
Never mind, I see now that this is actually more correct, looking at the rest of the file.  Sorry about that.

2021-02-19 06:06 UTC, closed without merging